---
- name: "Deploy Kubernetes Cluster"
  import_playbook: deploy-kubernetes.yml

- name: "Gather facts from control plane"
  hosts: controlplane
  gather_facts: true

- name: "Deploy Worker"
  hosts: worker
  gather_facts: true
  roles:
    - k8s-worker
